### ISSUE TITLE
The source of POLE samples

### ISSUE THREAD

**Issue by zhiiiyang** [friend1ws/pmsignature_paper#1]
Hi, I noticed that you included a list of POLE samples in this repository. May I ask where you found this information? Thank you!
https://github.com/friend1ws/pmsignature_paper/blob/master/backup/figure20150516/data/POLE_sample.txt

**Comment by friend1ws** [comment]
Hi, I believe I have extracted these samples based on the amount of "membership" of POLE signatures. This sample list is used for comparing the strengths of tow POLE related signatures. Since POLE signatures are split into two in pmsignature paper (signature1 & 8), I wanted to check the co-occurrence of these two signatures.
 `pmsignature_paper/backup/figure20150516/script/AlexandrovEtAl_poleMembership.R`
These are actually not used in the paper.

**Comment by zhiiiyang** [comment]
Thank you for information. Actually, whatever you did turns out be quite accurate in terms of identifying the POLE samples in cancer samples of colorectum and uterus. The reason that I asked you about the reference is becasue I also found a list of POLE sample from this paper by [Shinbrot, Eve, et al](https://genome.cshlp.org/content/24/11/1740.long) that you happened to cite in the pmsignature paper. One of the supplemental [table](https://genome.cshlp.org/content/24/11/1740/suppl/DC1) provides a list of POLE sample which is almost identical to your list on CRC and ECC, which I originally thought you extracted information from there. The result is also consistent with the fact that two POLE signatures were only found in cancers in [colorectrum and Uterus](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1005657). Also, signature 1 and 8 didn't get detected in other cancers like bladder, breast and etc., in which the COSMIC siganture 10 did. I am not sure if this could be possible due to the split too. Anyway, thank you for the clarification again! Great work.
